# settings.py

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 500
FPS = 60

GROUND_Y = 450

TITLE = "Counter-Strike Runner"

FONT_NAME = "emulogic"
FONT_FILE = BASE_DIR / "assets" / "fonts" / "emulogic.ttf"
TEXT_ANTIALIAS = False

SOUND_DIR = BASE_DIR / "assets" / "sounds"
JUMP_SOUND_FILE = SOUND_DIR / "jump.wav"
NEXT_LEVEL_SOUND_FILE = SOUND_DIR / "next_level.wav"
GAME_OVER_SOUND_FILE = SOUND_DIR / "game_over.wav"

UI_ASSET_DIR = BASE_DIR / "assets" / "ui"
RESTART_BUTTON_IMAGE_FILE = UI_ASSET_DIR / "restart_button.png"

DECORATION_ASSET_DIR = BASE_DIR / "assets" / "decorations"
CLOUD_IMAGE_FILE = DECORATION_ASSET_DIR / "cloud.png"
CLOUD_COUNT = 4
CLOUD_MIN_Y = 25
CLOUD_MAX_Y = 130
CLOUD_MIN_WIDTH = 45
CLOUD_MAX_WIDTH = 90
CLOUD_SPEED = 1.5

OBSTACLE_ASSET_DIR = BASE_DIR / "assets" / "obstacles"
CHICKEN_IMAGE_FILE = OBSTACLE_ASSET_DIR / "chicken.png"
CRATE_IMAGE_FILE = OBSTACLE_ASSET_DIR / "crate.png"
ENEMY_IMAGE_FILE = OBSTACLE_ASSET_DIR / "enemy.png"
GRENADE_IMAGE_FILE = OBSTACLE_ASSET_DIR / "grenade.png"
MOLOTOV_IMAGE_FILE = OBSTACLE_ASSET_DIR / "molotov.png"
AIRBORNE_OBSTACLE_SCORE = 200
AIRBORNE_LOW_CLEARANCE = 20
AIRBORNE_MID_CLEARANCE = 50
AIRBORNE_HIGH_CLEARANCE = 80

# Player settings
PLAYER_ASSET_DIR = BASE_DIR / "assets" / "player"
PLAYER_RUN_FRAME_FILES = (
    PLAYER_ASSET_DIR / "run_1.png",
    PLAYER_ASSET_DIR / "run_2.png",
)
PLAYER_CROUCH_FRAME_FILES = (
    PLAYER_ASSET_DIR / "crouch_1.png",
    PLAYER_ASSET_DIR / "crouch_2.png",
)
PLAYER_JUMP_FILE = PLAYER_ASSET_DIR / "jump.png"

PLAYER_START_X = 120
PLAYER_WIDTH = 70
PLAYER_STANDING_HEIGHT = 90
PLAYER_CROUCHING_HEIGHT = 50
PLAYER_RUN_ANIMATION_INTERVAL = 8
PLAYER_CROUCH_ANIMATION_INTERVAL = 8

GRAVITY = 0.9
JUMP_STRENGTH = -17

# Game settings
STARTING_SPEED = 6.0
MAX_SPEED = 15.0
SPEED_ACCELERATION = 0.002
SCORE_FLASH_COUNT = 4
SCORE_FLASH_INTERVAL = 15

MIN_OBSTACLE_GAP_PIXELS = 350
MAX_OBSTACLE_GAP_PIXELS = 650

# Colours
BACKGROUND_COLOR = (247, 247, 247)
GROUND_COLOR = (247, 247, 247)
GROUND_LINE_COLOR = (89, 89, 89)

TEXT_COLOR = (89, 89, 89)
